### ISSUE TITLE
Java Security Provider unsupported for SslProvider: OPENSSL

### ISSUE THREAD

**Issue by Seanspt** [jcrist/yarnspawner#10]
I'm trying yarnspawner out and get the following ERROR.
```bash
WARNING: log4j.properties is not found. HADOOP_CONF_DIR may be incomplete.
19/04/29 17:42:07 DEBUG skein.Driver: Starting Skein version 0.7.1
19/04/29 17:42:07 DEBUG skein.Driver: Logging in using ticket cache
19/04/29 17:42:08 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/29 17:42:08 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
19/04/29 17:42:09 ERROR skein.Driver: Error running Driver
java.lang.IllegalArgumentException: Java Security Provider unsupported for SslProvider: OPENSSL
	at com.anaconda.skein.shaded.io.netty.handler.ssl.SslContext.verifyNullSslContextProvider(SslContext.java:439)
	at com.anaconda.skein.shaded.io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:421)
	at com.anaconda.skein.shaded.io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:447)
	at com.anaconda.skein.Driver.startServer(Driver.java:127)
	at com.anaconda.skein.Driver.run(Driver.java:284)
	at com.anaconda.skein.Driver.main(Driver.java:174)
```

The jupyterhub server is hosted on my mac. Java and hadoop client is installed by homebrew. Hadoop configure files are downloaded from hadoop cluster master node and  $HADOOP_CONF_DIR is set.

The jupyterhub config file is as followed. Only `spawner_class` is configured. The hadoop cluster connected to is not kerberos-enabled, so I left security options as default. 
```python
c.JupyterHub.spawner_class = 'yarnspawner.YarnSpawner'
```

Any thing missing to end up to this ERROR?

**Comment by jcrist** [comment]
Why are you running this on your mac? YarnSpawner needs access to both the HDFS and YARN RPC endpoints, and is designed to be run from within the cluster (typically an edge node). Since Hadoop is commonly run on Linux only, [Skein](https://github.com/jcrist/skein) (the underlying YARN library) removes native dependencies for other OS's when building to minimize jar size. I recommend reading and following the instructions here: https://jcrist.github.io/jupyterhub-on-hadoop/manual-spawner.html

**Comment by Seanspt** [comment]
Thanks for your reply.
Yes, It seems to be a platform issue. I run jupyterhub in a docker container built from Centos, it just worked fine.
Most tools we use are cross-platform, so usually our develop environment is just on our laptops.  That's why I run this on my mac at the beginning.

Again, thanks for the great work you've done.
