### ISSUE TITLE
can not get user info from yarnspawner

### ISSUE THREAD

**Issue by reallyhappypig** [jcrist/yarnspawner#11]
when  i open a notebook on yarn ,the apihandler will make a mistake with message ' coroutine has no attrubute spawner ' in the line 'user.spawner.current_port = port' ,i print some log, it sames that the user is none.
so ,i use  'user = self._jupyterhub_user '   instead of 'user = self.get_current_user()', it works!
should i do this? 
is it a question? or i should config somethings spacial?

**Comment by jcrist** [comment]
Looks like the JupyterHub internals changed, breaking that code. It should be `user = self.current_user` instead of `user = self.get_current_user()` (which is now a coroutine). Care to make a PR making this change?

**Comment by reallyhappypig** [comment]
Thanks for you reply. 
I try to use self.current_user for test, it works!
I have make a PR use self.current_user instead of user = self.get_current_user().
