### ISSUE TITLE
Support hdfs and s3 path as user home.

### ISSUE THREAD

**Issue by Seanspt** [jcrist/yarnspawner#9]

**Comment by Seanspt** [comment]
Great work to have yarn integrated!
We are considering this option to achieve dynamic resource allocation for our jupyter users.
It would be a nice feature to have user home hosted on a remote file system rather than on local disk.

**Comment by jcrist** [comment]
By "Home" I assume you mean where the notebooks are stored? This isn't handled by the spawner but by the contents manager. A few good options are:

- HDFS: https://jcrist.github.io/hdfscm/
- S3/GCS: https://github.com/danielfrg/s3contents
- Postgres: https://github.com/quantopian/pgcontents

I recommend reading the [contents-managers](https://jcrist.github.io/jupyterhub-on-hadoop/contents-managers.html) section of the [jupyterhub-on-hadoop](https://jcrist.github.io/jupyterhub-on-hadoop/index.html) documentation. This discussing how to install and configure these options as part of a larger JupyterHub install.

**Comment by Seanspt** [comment]
Thanks a lot. We'll check it.
